# Generated by Django 4.1.7 on 2023-03-11 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_booking_email_remove_booking_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='accomodation',
            field=models.IntegerField(choices=[(0, 'resort'), (1, 'hotel')], default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='transport',
            field=models.IntegerField(choices=[(0, 'taxi'), (1, 'bus')], default=0),
        ),
    ]
