# Generated by Django 4.1.7 on 2023-03-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_booking_accomodation_booking_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='username',
            field=models.CharField(blank=True, max_length=116, null=True),
        ),
    ]
